/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sge.gui;

import com.sge.bs.DaoEnum;
import com.sge.bs.DaoFactory;
import com.sge.dao.SesionDao;
import com.sge.entity.Sesion;
import com.sge.tables.SesionTableValue;
import java.util.List;

/**
 *
 * @author dante
 */
public class ListSesionGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListSesionGUI
     */
    
    private static ListSesionGUI instancia;
           
    private ListSesionGUI() {
        initComponents();
  
    }
    
    public static ListSesionGUI getInstance() {
        
        try {
            if(instancia==null) {                
                instancia=new ListSesionGUI();
            }
        } catch (Exception e) {
            System.out.println("Siglenton Error:: "+ e);
        }
        
        return instancia;
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Secciones");

        List<Sesion> sesiones = sesionDao.getAll();
        SesionTableValue tv = new SesionTableValue(sesiones);
        jTable1.setModel(tv);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    SesionDao sesionDao = (SesionDao) DaoFactory.getDao(DaoEnum.SESION);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
