/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sge.gui;

import java.awt.Component;
import javax.swing.Box;

/**
 *
 * @author dante
 */
public class MenuEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form EstudienateMenu
     */

    String username;
    public MenuEstudiante(String user) {
        
        this.username=user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Pane1Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuBuscar = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuSecciones = new javax.swing.JMenu();
        jMenuGestionar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuSeccionClose = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        jMenu.setText("Estudiante");

        jMenuBuscar.setText("Buscar");
        jMenuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarActionPerformed(evt);
            }
        });
        jMenu.add(jMenuBuscar);

        jMenuItem3.setText("Inscribir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem3);

        jMenuBar1.add(jMenu);

        jMenuSecciones.setText("Secciones");

        jMenuGestionar.setText("Gestionar");
        jMenuGestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionarActionPerformed(evt);
            }
        });
        jMenuSecciones.add(jMenuGestionar);

        jMenuBar1.add(jMenuSecciones);

        jMenu3.setText(this.username);
        jMenu3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuSeccionClose.setText("Cerrar Seccion");
        jMenuSeccionClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSeccionCloseActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuSeccionClose);

        jMenuBar1.add(Box.createHorizontalGlue());

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pane1Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pane1Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSeccionCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSeccionCloseActionPerformed
       
         for (Component compo: Pane1Desktop.getComponents())
            compo.setVisible(false);
        
        new Login().show();
        this.dispose();
        
    }//GEN-LAST:event_jMenuSeccionCloseActionPerformed
 
    private void jMenuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarActionPerformed
        
       FindEstudianteGUI legui=FindEstudianteGUI.getInstance();
        if(!legui.isVisible())
            Pane1Desktop.add(legui);
        legui.setVisible(true);
        
    }//GEN-LAST:event_jMenuBuscarActionPerformed

    private void jMenuGestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionarActionPerformed
        // TODO add your handling code here:
        ListSesionGUI lsgui= ListSesionGUI.getInstance();
        if(!lsgui.isVisible())
            Pane1Desktop.add(lsgui);
        lsgui.setVisible(true);
    }//GEN-LAST:event_jMenuGestionarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        InscripsionEstudienate inscripcion = new InscripsionEstudienate();
        Pane1Desktop.add(inscripcion);
        inscripcion.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane Pane1Desktop;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuBuscar;
    private javax.swing.JMenuItem jMenuGestionar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuSeccionClose;
    private javax.swing.JMenu jMenuSecciones;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
